package ${config.outputpackage}.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

import com.alibaba.fastjson.JSONObject;
import com.insigma.business.components.hyfield.HYBeanUtil;
import com.insigma.business.components.hyfield.PageDao;
import com.insigma.framework.exception.AppException;
import com.insigma.odin.framework.datasource.SQLProcessor;
import com.insigma.odin.framework.persistence.HBSession;

import ${config.outputpackage}.entity.${entity};
import ${config.outputpackage}.dto.${entity}Dto;

/**
 * 
 * @author generated by hfree
 * @date ${time}
 */
@Repository
public class ${name}Dao extends PageDao{

	@Autowired
	private HBSession session;

${content}

}
