package ${config.outputpackage}.enums;

import com.insigma.business.ZZGBGL.ZZGBGL_PUB.ZZGBGL_PUB002.service.BaseExceptionAssert;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 异常类
 * @author generated by hfree
 * @date ${time}
 */
@Getter
@AllArgsConstructor
public enum ${name}Enum implements BaseExceptionAssert {

	${entity}_NOT_FOUND(2001, "获取${tablecomment}失败！"),
	exception(0000, "自定义！")
    ;
    
    /** 获取返回码 */
    private int code;

    /** 获取返回消息 */
    private String message;
}
 

