package ${config.outputpackage}.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 流程模型环节编码
 * @author generated by hfree
 * @date ${time}
 */
@Getter
@AllArgsConstructor
public enum ${name}M0213Enum {

	草稿("00", "草稿")
    ;
    
    /** 流程编码 */
    private String code;

    /** 流程名字 */
    private String name;
}
 

