package ${config.outputpackage}.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 流程业务状态码
 * @author generated by hfree
 * @date ${time}
 */
@Getter
@AllArgsConstructor
public enum ${name}${entity}60Enum {

	草稿("00","业务信息录入")
    ;
    
    /** 状态码 */
    private String code;
    private String msg;
}
 

