package ${config.outputpackage}.service;

import java.util.List;
import java.util.Map;

import com.alibaba.fastjson.JSONObject;
import com.insigma.framework.exception.AppException;

import ${config.outputpackage}.entity.${entity};
import ${config.outputpackage}.dto.${entity}Dto;

/**
 * 
 * @author generated by hfree
 * @date ${time}
 */
public interface ${name}Service {

${content}

}
